### ISSUE TITLE
Grandma Soup Issue

### ISSUE THREAD

**Issue by jet8858** [the-isf-academy/quest#24]
When I'm walking around getting vegetables in the grandma soup game a pop-up message would start popping up and would not go away, even after I press enter. They would just go down for a second then pop back up.

**Comment by cproctor** [comment]
I think I fixed this issue with 0233d53a22a0a97cc803f031ec1cf31db46af840. Can you try pulling the latest code? 

The problem was that Grandma was opening the dialogue modal whenever she experienced a collision. This is correct behavior when she collides with the player, but not correct when she collides with a wall. Furthermore, her movement strategy isn't very sophisticated so she sometimes spends quite a bit of time walking into the same wall.
