### ISSUE TITLE
Attack System

### ISSUE THREAD

**Issue by kayn0111034** [the-isf-academy/quest#27]
**Describe the feature**
You can choose  to run away or talk or fight

**Example usages**
When the main character runs into an NPC they enter the attack system

**Comment by wolfj95** [comment]
This could potentially be a really large feature. In your proposal, you separated the attack system from the battle system. This is a good idea for feature development too.

Focus first on creating an example where you run into NPCs and have and choose whether to run, talk, or fight. This could use the existing modal system for dialogue.

Make sure that it is built in a way so that i can easily hand off the interaction to a battle system if the attack option is chosen once the battle system is created. You might even build what's called a "stub" class for the battle system that can be called at the right time but don't actually implement any functionality of the battle system.

**Comment by cproctor** [comment]
This was submitted in #41, which implemented part of the feature. I agree with @wolfj95 that this is actually several features combined together. Let's break them out and develop them one at a time!

**Comment by kayn0111034** [comment]
I think we did a pretty good job of making the attack system.
Developing this feature was harder than expected.
Next time we could probably try starting from a smaller function and build it up.

**Comment by scar34680** [comment]
Overall, I think we did pretty well on this project. Even though we didn't completely finish in time, I think we can further develop this system in the future. Since this is a big part of our final unit project, it is really helpful that we completed some of the coding before the project even started. As a group, it was pretty challenging to develop this feature as there are many different components.
